// 幸福超市 — the corner shop on the ground floor of your block, from the inside.
//
// A Chinese 超市 of this size is a particular room: a hard tiled floor, bare fluorescent tubes
// in a low ceiling, compact aisles that still let two shoppers turn past one another, a chest
// freezer humming against one wall, a wall of instant noodles, and a till by the door with a stool
// behind it. The whole
// shop is about seven metres by six, which is what makes it feel like a shop rather than a
// warehouse — you are never more than a couple of steps from a shelf.
//
// The shopfront glazing is on the -z wall, facing the alley, because the renderer projects
// daylight through one named opening and its test assumes the sun arrives from -z. Every
// interior in this game therefore puts its window on that wall.
const Shop = Lazy('Shop', () => {
  // The grade. A 便利店 is lit hard and white from overhead and everything in it is printed
  // paper, so the room's own surfaces have to sit *below* the goods or the goods disappear:
  // the floor and the shelving carry a little more weight than they used to, and the ceiling
  // — which is the light in this room — stays where it is. Flattening those two together was
  // what made the place read as a lightbox with some boxes in it.
  const col = {
    floor: C('#cdc7b8'), grout: C('#a6a094'), wall: C('#e2ddce'), ceil: C('#f2f0e8'),
    grid: C('#d6d2c6'),
    trim: C('#b9b5ab'), steel: C('#a2a9af'), steelD: C('#6f767c'), chrome: C('#c6ccd0'),
    white: C('#f2f0e9'), cream: C('#e8dfcf'), charcoal: C('#2f343a'), black: C('#1b1e22'),
    red: C('#c0402a'), redD: C('#8c2f20'), gold: C('#d5a336'), goldL: C('#e8c25c'),
    green: C('#4c7a45'), greenD: C('#365a33'), jade: C('#3f7564'),
    blue: C('#3a6a92'), blueL: C('#5b8cb4'), navy: C('#27364a'),
    orange: C('#d97a2b'), yellow: C('#e2b83a'), pink: C('#c4657a'), purple: C('#7a5f96'),
    wood: C('#8a6a44'), woodD: C('#5c452c'), lino: C('#cfcabd'),
    glass: C('#c3d6e2'), fridge: C('#dfe6e8'), tube: C('#f4f6ee'),
    card: C('#c9ac82'), cardD: C('#a98d66'),
    // Shelf-edge furniture and the packaging hues the muted list was missing. A Chinese shelf
    // is not five colours: it is every colour, printed cheaply, which is a spread of hue at a
    // *middling* saturation rather than a handful of fully saturated primaries.
    tick: C('#f6f4ec'), tickR: C('#cf3f2c'),
    magenta: C('#b0446e'), teal: C('#2f7f86'), lime: C('#8aa63c'), sky: C('#7fb4d6'),
    amber: C('#e08a24'), plum: C('#6b4a72'), rust: C('#a8542c'),
  };
  const G = { matte: .06, wood: .20, paint: .16, metal: .58, glass: .80, fabric: .04 };

  const B = Build.scene({ fabricGloss: G.fabric });
  const { box, cyl, ball, capsule, taper, wall, flat, glyphs,
          solid, shade, glow, thing } = B;

  // ---------------------------------------------------------------- dimensions
  // Half-extents, so the room runs -RX..RX and -RZ..RZ with the shopfront at -RZ.
  const RX = 3.6, RZ = 3.0, H = 2.60;
  const WIN = { x: 0, y: 1.42, z: -RZ + .06, hw: 1.55, hh: .95 };
  const DX = 2.35;                        // x of the door in the shopfront
  // Where you land on the pavement when you leave. The shopfront on the street is centred on
  // Street.SHOP, and the door sits at the +x end of it.
  const OUT = { x: 7.6 + 1.55, z: -2.95 + 1.75, yaw: Math.PI * .5 };

  const litProps = [], doorParts = [], fanBlades = [];
  function litten(p, k) { litProps.push({ p, k }); return p; }
  function movingDoor(p) {
    const sx=Math.hypot(p.m[0],p.m[1],p.m[2]);
    const sy=Math.hypot(p.m[4],p.m[5],p.m[6]);
    const sz=Math.hypot(p.m[8],p.m[9],p.m[10]);
    doorParts.push({p,m0:new Float32Array(p.m),ob:p.ob&&{...p.ob}});
    // A hinged leaf sweeps about half a metre from its built centre. Preserve that whole arc in
    // the packed cull data generated by finish().
    p.fixed=true; p.cx=p.m[12]; p.cy=p.m[13]; p.cz=p.m[14];
    p.r=.5*Math.hypot(sx,sy,sz)+.62;
    return p;
  }

  let seed = 0x51109;
  const rnd = () => (seed = (seed * 1103515245 + 12345) & 0x7fffffff) / 0x7fffffff;
  const pick = a => a[(rnd() * a.length) | 0];

  // ---------------------------------------------------------------- 价格 what the shop sells
  // Five things you can take off a shelf, what each one costs, and what it is worth to you.
  // The tickets on the fixtures are printed from this list and so is the total at the till, so
  // the number on the shelf edge and the number you are charged cannot drift apart.
  //
  // `keeps` is how many meals it puts in the fridge at home. `gain` is what you get on the spot,
  // for the things you open on the way out rather than carry home.
  // `at`/`yaw` is where the ticket goes and which way it faces. Two of them hang on the wall
  // behind their goods and one stands on a wire spike in the fruit, because the fixtures
  // themselves are full: a card pushed onto the front of the noodle wall lands halfway through
  // a row of pot lids, and one on the rice sacks lands in the printed panel.
  // ---- 商品 what the shop sells, and where the tickets that say so are nailed up.
  //
  // These five rows are *fixtures*: each one is a place in the room with a printed price ticket
  // on it, and `at`/`yaw`/`spike` are that ticket's position. Do not add a row without a place to
  // hang it — the ticket loop below reads `g.at` off every one of them.
  //
  // Three of the five are a single product you reach down: a pot of noodles, a bag of fruit, a
  // sack of rice. The other two are not products at all, they are furniture — 货架 is a gondola
  // of dry goods and 冰柜 is the chiller — and one price on a whole gondola was the shop's oldest
  // lie. You "took some off the shelf" and got an abstraction worth nine kuai.
  //
  // So those two open their contents instead (see SHELF), their ticket prints the cheapest thing
  // on them with 起 after it the way a real one does, and `price` here is that cheapest thing.
  const GOODS = [
    { hz:'方便面', price:4,  at:[-2.60, 1.92, 2.94], yaw:Math.PI },
    { hz:'水果',   price:12, at:[-1.90, .80, -2.22], yaw:Math.PI, spike:.26 },
    { hz:'米',     price:20, at:[-3.55, 1.24, .55], yaw:Math.PI / 2 },
    { hz:'货架',   price:3,  from:true, at:[.80, .99, -.462], yaw:Math.PI },
    { hz:'冰柜',   price:4,  from:true, at:[2.63, .78, -.34], yaw:-Math.PI / 2 },
  ];

  // ---- what is actually on the two open fixtures.
  //
  // Cheapest first, because that is the order the eye goes down a shelf and because the first row
  // is the one the ticket outside is quoting. Everything here is a product Pantry knows and a word
  // the dictionary has: a row that is neither is a crash at the panel rather than a missing line.
  //
  // The point of listing them by name is not the shopping. It is that this is a wall of Chinese
  // with numbers next to it, which is the surface a price is misread on — and a shopping trip you
  // can get wrong is the only kind worth simulating.
  const SHELF = {
    '货架': [
      { hz:'盐',     price:3 },
      { hz:'面条',   price:6 },
      { hz:'酱油',   price:8 },
      { hz:'油',     price:14 },
      { hz:'土豆',   price:3 },
      { hz:'西红柿', price:4 },
      { hz:'白菜',   price:6 },
      { hz:'蔬菜',   price:9 },
      { hz:'鸡蛋',   price:11 },
      { hz:'面包',   price:8 },
    ],
    '冰柜': [
      { hz:'饮料',   price:4 },
      { hz:'酸奶',   price:6 },
      { hz:'牛奶',   price:7 },
      { hz:'肉馅',   price:16 },
      { hz:'猪肉',   price:18 },
      { hz:'鸡肉',   price:19 },
      { hz:'鱼',     price:22 },
      { hz:'牛肉',   price:26 },
    ],
  };

  // ---------------------------------------------------------------- 商品 the goods themselves
  //
  // Every packet on every shelf used to be one box: `box(..., pick(palette))`, a row of identical
  // cuboids in five colours, four decks of them, twice. At a metre away that is not a supermarket,
  // it is a pallet of bricks, and it was the first thing anybody noticed walking in.
  //
  // These are the things actually on the shelves of a 便利店 in a Beijing hutong. Each is a handful
  // of primitives — a body, a lid, a band of label — because the budget here is prop count and not
  // detail: the two gondolas carry well over half of this room's props, so an item that costs six
  // draws instead of three costs the shop a thousand of them.
  //
  // What makes them read is not the polygon count. It is that a bottle has a neck and a cap, that a
  // cup of noodles is wider at the top than the bottom, that a rice sack is cloth and slumps, and
  // above all that the same product stands several facings wide the way stock actually does — a
  // shelf where every neighbour is a different thing is a jumble sale, not a shop.
  const GOOD = {};

  // Where a printed panel goes. Every builder is handed the yaw of the face it is standing on,
  // and its label belongs on *that* face. Offsetting the panel along world +z instead — which is
  // what this did — leaves one whole side of every gondola with its printing turned into the
  // shelf, and the chiller with all of it turned along the glass instead of through it.
  const face = (x, z, ry, d) => [x + Math.sin(ry) * d, z + Math.cos(ry) * d];

  // 方便面 a pot of instant noodles: tapered tub, foil lid, printed band round the middle.
  GOOD.cup = (x, y, z, ry, T, c) => {
    taper(x, y + .055, z, .105, .11, .105, c.body, { gloss: .26, ry, ...T });
    cyl(x, y + .114, z, .056, .012, col.white, { gloss: .30, ry, ...T });
    cyl(x, y + .055, z, .053, .05, c.trim, { gloss: .24, ry, ...T });
  };
  // 桶面 the big bucket version, which every shop stacks on the top deck
  GOOD.bucket = (x, y, z, ry, T, c) => {
    taper(x, y + .085, z, .145, .17, .145, c.body, { gloss: .26, ry, ...T });
    cyl(x, y + .175, z, .075, .014, col.cream, { gloss: .30, ry, ...T });
  };
  // 酱油 · 醋 soy sauce and vinegar: a dark bottle with a shoulder, a neck and a bright cap.
  GOOD.bottle = (x, y, z, ry, T, c) => {
    box(x, y + .085, z, .072, .17, .072, c.body, { gloss: .62, ry, ...T });
    taper(x, y + .196, z, .066, .06, .066, c.body, { gloss: .62, ry, ...T });
    cyl(x, y + .243, z, .019, .036, c.cap, { gloss: .40, ry, ...T });
    const [lx, lz] = face(x, z, ry, .038);
    box(lx, y + .085, lz, .062, .085, .006, c.label, { hard: true, gloss: .20, ry, ...T });
  };
  // 白酒 a squat ceramic spirit bottle, and 啤酒 a tall green one. The same shape, different build.
  GOOD.tallBottle = (x, y, z, ry, T, c) => {
    cyl(x, y + .095, z, .036, .19, c.body, { gloss: .70, ry, ...T });
    taper(x, y + .215, z, .058, .06, .058, c.body, { gloss: .70, ry, ...T });
    cyl(x, y + .262, z, .014, .038, c.cap, { gloss: .50, ry, ...T });
    cyl(x, y + .095, z, .038, .07, c.label, { gloss: .18, ry, ...T });
  };
  // 大米 a sack of rice: cloth, so it slumps, and mode 7 gives it a weave.
  GOOD.sack = (x, y, z, ry, T, c) => {
    box(x, y + .075, z, .30, .15, .19, c.body,
      { mode: 7, gloss: .10, round: .055, ry,
        mat: 'fabric', matScale: .20, matAmt: .32, ...T });
    // The stitched seam along the top, which is the one line that says sack rather than pillow.
    box(x, y + .146, z, .27, .022, .10, c.seam || c.label,
      { mode: 7, gloss: .12, ry, ...T });
    // And the printed panel, big enough to be the thing you see: a bag of rice in a Chinese shop
    // is mostly print.
    const [lx, lz] = face(x, z, ry, .098);
    box(lx, y + .072, lz, .215, .105, .012, c.label, { hard: true, gloss: .16, ry, ...T });
  };
  // 茶叶 a tea caddy, and 罐头 a tin: a cylinder with a rim, which is all a tin is.
  GOOD.tin = (x, y, z, ry, T, c) => {
    cyl(x, y + .058, z, .044, .116, c.body, { gloss: .44, ry, ...T });
    cyl(x, y + .118, z, .046, .010, c.cap, { gloss: .52, ry, ...T });
  };
  // 饼干 · 麦片 a carton, standing up, with the printed panel facing out.
  GOOD.carton = (x, y, z, ry, T, c) => {
    box(x, y + .105, z, .145, .21, .065, c.body, { hard: true, gloss: .18, ry, ...T });
    const [lx, lz] = face(x, z, ry, .036);
    box(lx, y + .125, lz, .105, .085, .006, c.label, { hard: true, gloss: .16, ry, ...T });
  };
  // 牛奶 a gable-top milk carton, which is the one silhouette in a shop nothing else has.
  GOOD.milk = (x, y, z, ry, T, c) => {
    box(x, y + .075, z, .085, .15, .085, c.body, { hard: true, gloss: .22, ry, ...T });
    taper(x, y + .175, z, .085, .06, .085, c.body, { hard: true, gloss: .22, ry, ...T });
    const [lx, lz] = face(x, z, ry, .046);
    box(lx, y + .075, lz, .062, .07, .006, c.label, { hard: true, gloss: .18, ry, ...T });
  };
  // 薯片 · 辣条 a bag of crisps: inflated, so it is round-cornered and wider in the middle, with
  // the crimped seal along the top.
  GOOD.bag = (x, y, z, ry, T, c) => {
    box(x, y + .105, z, .155, .20, .085, c.body,
      { gloss: .34, round: .05, ry, ...T });
    box(x, y + .212, z, .150, .022, .020, c.trim, { hard: true, gloss: .30, ry, ...T });
  };
  // 卫生纸 a bale of toilet rolls, which in a shop this size lives on the top deck.
  GOOD.rolls = (x, y, z, ry, T, c) => {
    box(x, y + .115, z, .225, .23, .155, c.body,
      { gloss: .16, round: .06, ry, ...T });
    const [lx, lz] = face(x, z, ry, .082);
    box(lx, y + .13, lz, .13, .09, .006, c.label, { hard: true, gloss: .14, ry, ...T });
  };
  // 瓶装水 bottled water: clear, so it is mostly its blue cap and its label.
  GOOD.water = (x, y, z, ry, T, c) => {
    cyl(x, y + .085, z, .032, .17, col.glass, { gloss: .78, alpha: .55, ry, ...T });
    cyl(x, y + .085, z, .034, .055, c.label, { gloss: .22, ry, ...T });
    cyl(x, y + .188, z, .015, .036, c.cap, { gloss: .46, ry, ...T });
  };
  // 冰淇淋 a tub of ice cream, and 酸奶 a pot of yoghurt: the same shape at two sizes.
  GOOD.tub = (x, y, z, ry, T, c) => {
    taper(x, y + .056, z, .125, .112, .125, c.body, { gloss: .30, ry, ...T });
    cyl(x, y + .118, z, .068, .016, c.cap, { gloss: .36, ry, ...T });
  };
  // 饺子 a bag of frozen dumplings, standing on end in the chest the way they are stacked. Sized
  // to fill a chest freezer to the glass: a bag that stops short of the rim is a chest that reads
  // as empty from anywhere except directly overhead, which is nowhere the player ever stands.
  GOOD.frozen = (x, y, z, ry, T, c) => {
    box(x, y + .170, z, .30, .34, .26, c.body,
      { mode: 7, gloss: .34, round: .05, ry, ...T });
    const [lx, lz] = face(x, z, ry, .134);
    box(lx, y + .190, lz, .21, .18, .008, c.label, { hard: true, gloss: .22, ry, ...T });
  };
  // 腐乳 · 辣椒酱 a squat glass jar with a screw lid. The one silhouette on a condiment shelf
  // that is neither a bottle nor a box, and without it the whole deck is verticals.
  GOOD.jar = (x, y, z, ry, T, c) => {
    cyl(x, y + .052, z, .050, .104, c.body, { gloss: .66, ry, ...T });
    cyl(x, y + .112, z, .046, .026, c.cap, { gloss: .44, ry, ...T });
    cyl(x, y + .050, z, .052, .052, c.label, { gloss: .20, ry, ...T });
  };
  // 榨菜 · 调料 a stand-up foil pouch: narrow, flat, and taller than it is wide, so a row of
  // them breaks up a deck of round things the way the real ones do.
  GOOD.pouch = (x, y, z, ry, T, c) => {
    box(x, y + .080, z, .092, .16, .042, c.body,
      { gloss: .46, round: .028, ry, ...T });
    box(x, y + .166, z, .086, .020, .014, c.trim, { hard: true, gloss: .40, ry, ...T });
  };
  // 易拉罐 a slim can: body, a bright band round the middle, and the dull lid on top.
  GOOD.can = (x, y, z, ry, T, c) => {
    cyl(x, y + .066, z, .033, .132, c.body, { gloss: .58, ry, ...T });
    cyl(x, y + .066, z, .035, .056, c.label, { gloss: .34, ry, ...T });
    cyl(x, y + .134, z, .030, .008, col.chrome, { gloss: .60, ry, ...T });
  };
  // 五连包 five bagged noodles shrink-wrapped into a slab, which is how they are actually sold
  // and the one item on the shelf that is wider than it is tall.
  GOOD.pack = (x, y, z, ry, T, c) => {
    box(x, y + .058, z, .27, .115, .10, c.body,
      { gloss: .40, round: .030, ry, ...T });
    const [lx, lz] = face(x, z, ry, .054);
    box(lx, y + .062, lz, .20, .072, .008, c.label, { hard: true, gloss: .22, ry, ...T });
  };
  // 鸡蛋 a tray of eggs, open, because a closed one is a box and this has to read as eggs.
  GOOD.eggs = (x, y, z, ry, T) => {
    box(x, y + .022, z, .21, .044, .145, col.cardD, { gloss: .12, ry, ...T });
    for (let i = 0; i < 3; i++) for (const s of [-1, 1])
      ball(x - .062 + i * .062, y + .052, z + s * .034, .024, .020, .024,
        C('#e8dcc4'), { gloss: .26, ...T });
  };

  // Which products stand on which aisle. A shop is sorted, and a sorted shelf is most of what
  // separates a shop from a warehouse: noodles together, condiments together, drinks together.
  // Each entry is a builder, its colours, and how wide one facing of it is.
  const P = {
    cup:    { f: GOOD.cup, w: .215, c: { body: C('#c4402f'), trim: C('#e8c25c') } },
    cup2:   { f: GOOD.cup, w: .215, c: { body: C('#d97a2b'), trim: C('#f0e2c0') } },
    bucket: { f: GOOD.bucket, w: .30, c: { body: C('#b8402c') } },
    soy:    { f: GOOD.bottle, w: .155, c: { body: C('#33241c'), cap: C('#c9a13a'),
              label: C('#e8dfcf') } },
    vinegar:{ f: GOOD.bottle, w: .155, c: { body: C('#2b1f2a'), cap: C('#b8402c'),
              label: C('#dfd2b4') } },
    oil:    { f: GOOD.tallBottle, w: .17, c: { body: C('#c9a13a'), cap: C('#b8402c'),
              label: C('#f0e6cc') } },
    beer:   { f: GOOD.tallBottle, w: .155, c: { body: C('#3f5a2e'), cap: C('#c9a13a'),
              label: C('#e8dfcf') } },
    baijiu: { f: GOOD.tallBottle, w: .16, c: { body: C('#eae6dc'), cap: C('#b8402c'),
              label: C('#c4402f') } },
    rice:   { f: GOOD.sack, w: .34, c: { body: C('#e0d3b4'), label: C('#b8402c'),
              seam: C('#c0ae88') } },
    flour:  { f: GOOD.sack, w: .34, c: { body: C('#dfe4e8'), label: C('#3a6a92'),
              seam: C('#b9c2c9') } },
    tea:    { f: GOOD.tin, w: .115, c: { body: C('#3f7564'), cap: C('#c9a13a') } },
    tin:    { f: GOOD.tin, w: .115, c: { body: C('#b06a34'), cap: C('#c6ccd0') } },
    biscuit:{ f: GOOD.carton, w: .185, c: { body: C('#c9843a'), label: C('#f0e6cc') } },
    cereal: { f: GOOD.carton, w: .185, c: { body: C('#4e7286'), label: C('#e8dfcf') } },
    milk:   { f: GOOD.milk, w: .125, c: { body: C('#f2f0e9'), label: C('#3a6a92') } },
    juice:  { f: GOOD.milk, w: .125, c: { body: C('#e0a24a'), label: C('#f2f0e9') } },
    crisps: { f: GOOD.bag, w: .20, c: { body: C('#dfb43a'), trim: C('#b8402c') } },
    lat:    { f: GOOD.bag, w: .20, c: { body: C('#b8402c'), trim: C('#dfb43a') } },
    rolls:  { f: GOOD.rolls, w: .27, c: { body: C('#cfdeea'), label: C('#b8402c') } },
    water:  { f: GOOD.water, w: .095, c: { cap: C('#3a6a92'), label: C('#5b8cb4') } },
    cola:   { f: GOOD.water, w: .095, c: { cap: C('#b8402c'), label: C('#8c2f20') } },
    eggs:   { f: GOOD.eggs, w: .245, c: {} },
    jar:    { f: GOOD.jar, w: .115, c: { body: C('#8f3a2c'), cap: C('#c9a13a'),
              label: C('#e8dfcf') } },
    jar2:   { f: GOOD.jar, w: .115, c: { body: C('#5c6a2e'), cap: C('#b8402c'),
              label: C('#f0e6cc') } },
    pouch:  { f: GOOD.pouch, w: .115, c: { body: C('#b0446e'), trim: C('#e8dfcf') } },
    pouch2: { f: GOOD.pouch, w: .115, c: { body: C('#2f7f86'), trim: C('#f0e6cc') } },
    can:    { f: GOOD.can, w: .085, c: { body: C('#b8402c'), label: C('#dfb43a') } },
    can2:   { f: GOOD.can, w: .085, c: { body: C('#2f7f86'), label: C('#e8dfcf') } },
    can3:   { f: GOOD.can, w: .085, c: { body: C('#e08a24'), label: C('#8c2f20') } },
    pack:   { f: GOOD.pack, w: .295, c: { body: C('#c4402f'), label: C('#e8c25c') } },
    pack2:  { f: GOOD.pack, w: .295, c: { body: C('#8aa63c'), label: C('#f0e6cc') } },
    // the cold end: what is in the chest and behind the glass door
    dump:   { f: GOOD.frozen, w: .295, c: { body: C('#3a6a92'), label: C('#f0e6cc') } },
    dump2:  { f: GOOD.frozen, w: .295, c: { body: C('#b8402c'), label: C('#f0e2c0') } },
    bao:    { f: GOOD.frozen, w: .295, c: { body: C('#e8dfcf'), label: C('#3f7564') } },
    ice:    { f: GOOD.tub, w: .17, c: { body: C('#f2ece0'), cap: C('#b8402c') } },
    ice2:   { f: GOOD.tub, w: .17, c: { body: C('#9c6b46'), cap: C('#e8dfcf') } },
    yog:    { f: GOOD.tub, w: .17, c: { body: C('#f2f0e9'), cap: C('#3a6a92') } },
  };
  // Four decks, bottom to top, per aisle. Heavy and bulky low down, light and small at eye level,
  // and the bales of paper on top — which is how a shop is actually stacked, and it means the
  // things you look at are the things at the height you look.
  const AISLES = {
    dry:  [['rice', 'flour', 'rice', 'flour'],
           ['soy', 'vinegar', 'oil', 'jar', 'soy', 'jar2', 'vinegar'],
           ['tea', 'tin', 'pouch', 'tin', 'jar', 'tea', 'pouch2', 'jar2'],
           ['bucket', 'rolls', 'pack', 'bucket']],
    snack:[['water', 'cola', 'can', 'water', 'beer', 'can3', 'cola'],
           ['cup', 'cup2', 'pack', 'cup', 'bucket', 'cup2', 'pack2'],
           ['crisps', 'lat', 'pouch', 'crisps', 'can2', 'lat'],
           ['biscuit', 'cereal', 'rolls', 'biscuit', 'pack']],
  };

  // Lay one deck out as blocks of facings. `n` facings of a product, then the next product, until
  // the deck is full — with the occasional gap where somebody has already taken one, because a
  // perfectly faced shelf is a photograph of a shop rather than a shop.
  function stockDeck(cx, cz, len, y, ry, tag, aisle, deck, stop) {
    const kinds = AISLES[aisle][deck % 4];
    const T = { tag };
    let x = cx - len / 2 + .12;
    // `stop` is an optional stock-facing cutoff for variants where a shelf disappears behind a
    // taller fitted fixture. The current shop keeps every run physically separate, so neither
    // call needs it; retaining the parameter lets a future variant avoid authoring invisible
    // packets inside joinery without changing the shared shelf geometry.
    const edge = Math.min(cx + len / 2 - .10, stop === undefined ? Infinity : stop);
    let k = 0;
    while (x < edge && k < 40) {
      const p = P[kinds[k % kinds.length]];
      k++;
      // Two to four facings of the same thing, which is what a shelf looks like.
      const facings = 2 + ((rnd() * 3) | 0);
      for (let i = 0; i < facings && x < edge; i++) {
        if (rnd() > .09)
          p.f(x, y, cz, ry + (rnd() - .5) * .06, T, p.c);
        x += p.w;
      }
      x += .035;                            // the gap between one product and the next
    }
  }

  // ---------------------------------------------------------------- parts
  // A run of gondola shelving: uprights, a kick plate, and four decks of stock. Shelves are
  // where nearly all of the shop's prop budget goes, so one function makes them all and the
  // stock on each deck is a row of boxes and tins rather than modelled goods.
  // Shelving is a shell, not a block. Built as one solid volume with decks glued to its faces —
  // which is the obvious way to do it and what this was — every packet on every shelf ends up
  // inside the volume and invisible, and a supermarket becomes two grey slabs with a row of
  // boxes balanced on top. Back panel, two ends, a base and the decks; the stock stands on the
  // decks in the open air where it can be seen.
  function gondola(cx, cz, len, ry, tag, aisle, stop) {
    const T = { tag, ry };
    // Shop shelving is folded sheet steel, and the back panel of a run is four and a half
    // metres of it: the one surface in the room big enough that a flat fill reads as a painted
    // wall rather than as metal. `MET` is that sheet, kept to a 30 cm repeat: at 55 cm the
    // wear in the photograph came out at the size of the end cap itself and every gondola end
    // in the shop read as a damp stain rather than as steel. What is wanted off a surface
    // texture at this distance is grain, and grain has to be smaller than the thing it is on.
    const MET = { mat: 'metal', matScale: .30, matAmt: .26 };
    const half = len / 2;
    box(cx, .82, cz, len, 1.56, .05, col.steelD, { hard: true, gloss: .30, ...MET, ...T });
    for (const s of [-1, 1])
      box(cx + s * half, .82, cz, .05, 1.56, .56, col.steel,
        { hard: true, gloss: G.metal, ...MET, ...T });
    box(cx, .09, cz, len, .18, .60, col.steelD,
      { hard: true, gloss: G.metal, ...MET, ...T });
    box(cx, 1.62, cz, len, .05, .58, col.steel,
      { hard: true, gloss: G.metal, ...MET, ...T });
    for (let d = 0; d < 4; d++) {
      const y = .30 + d * .34;
      for (const s of [-1, 1]) {
        box(cx, y, cz + s * .16, len - .08, .030, .28, col.chrome,
          { hard: true, gloss: G.metal, mat: 'metal', matScale: .28, matAmt: .24, ...T });
        // The stock, faced up in blocks of one product at a time. The two sides of a gondola are
        // two different aisles, because you walk down both of them.
        stockDeck(cx, cz + s * .17, len - .16, y + .015,
          ry + (s < 0 ? 0 : Math.PI), tag, s < 0 ? aisle[0] : aisle[1], d, stop);
        // The price rail along the front edge of the deck, which is most of what says "shop".
        // Not one yellow bar: a shelf edge in a Chinese supermarket is a white ticket strip
        // with a yellow cap over it and red 特价 flashes clipped on at intervals, and it is the
        // repetition of that one detail down eight metres of shelving that reads as a shop.
        const e = stop === undefined ? cx + half : Math.min(cx + half, stop + .06);
        const rc = (cx - half + e) / 2, rl = e - (cx - half) - .10;
        box(rc, y - .045, cz + s * .300, rl, .042, .018, col.tick,
          { hard: true, gloss: .22, ...T });
        box(rc, y - .019, cz + s * .300, rl, .016, .020, col.yellow,
          { hard: true, mode: 1, ...T });
        for (let f = 0; f < 2; f++)
          box(cx - half + .30 + rnd() * (rl - .55), y - .050, cz + s * .316,
            .125, .078, .012, col.tickR, { hard: true, gloss: .20, ...T });
      }
    }
    // 备货 the overstock on the crown of the run. The metre between the top deck and the ceiling
    // is a metre of nothing in a model and a metre of cardboard in a shop: cases of the line
    // below, opened and half emptied, is where the back stock actually lives in a room this size.
    let ox = cx - half + .34;
    while (ox < cx + half - .40) {
      if (rnd() < .26) { ox += .30 + rnd() * .30; continue; }
      const w = .40 + rnd() * .20, h = .24 + rnd() * .12, yaw = ry + (rnd() - .5) * .20;
      const body = rnd() > .45 ? col.card : col.cardD;
      box(ox + w / 2, 1.66 + h / 2, cz, w, h, .46, body,
        { hard: true, gloss: .14, ry: yaw, tag,
          mat: 'plaster', matScale: .30, matAmt: .26 });
      for (const s of [-1, 1]) {
        const [px2, pz2] = face(ox + w / 2, cz, yaw + (s < 0 ? Math.PI : 0), .234);
        // The printed panel on the end of the case, in the full spread of cheap packaging hue
        // the palette above was widened for. Five colours is a set of building blocks; the point
        // of a wall of cardboard is that no two cases came off the same press.
        box(px2, 1.66 + h * .55, pz2, w * .58, h * .42, .010,
          pick([col.red, col.blue, col.green, col.amber, col.teal,
                col.magenta, col.lime, col.sky, col.plum, col.rust]),
          { hard: true, gloss: .16, ry: yaw, tag });
      }
      // Every third case gets one stacked on it, which is what stops the crown reading as a
      // single extruded ridge the length of the aisle.
      if (rnd() > .55)
        box(ox + w / 2 - .04, 1.68 + h + .12, cz + .03, w * .80, .24, .40,
          rnd() > .5 ? col.cardD : col.card,
          { hard: true, gloss: .14, ry: yaw + (rnd() - .5) * .3, tag });
      ox += w + .06;
    }
    solid(cx - half - .02, cx + half + .02, cz - .32, cz + .32);
    shade(cx, cz, len + .3, .9, .30);
  }

  // A fluorescent batten. Two of these and the room reads as a shop rather than a front room.
  function tube(cx, cz, len) {
    box(cx, H - .05, cz, len, .09, .22, col.steel,
      { hard: true, gloss: G.metal, mat: 'metal', matScale: .30, matAmt: .26 });
    // The lit face of the fitting stays a bare emissive strip: a texture on a mode-1 panel is
    // a photograph of dirt on something that is supposed to be the brightest thing in the room.
    litten(box(cx, H - .115, cz, len - .10, .04, .16, col.tube,
      { hard: true, mode: 1, glow: .46 }), 1);
    glow(M.trs(cx, .02, cz, 0, len + 1.6, 1, 2.6), C('#fff4dd'), .12);
    // And the batten as an actual light, which is new. The emissive strip above is what the
    // fitting looks like and the pool below is the patch it paints on the floor; neither of
    // them lit so much as a tin. A 便利店 is a room with nothing in it but overhead fluorescent,
    // so the tubes have to be the thing the goods are lit by or the shelves stay flat.
    // A four-metre run is not a point, and one light at its centre leaves both ends of the
    // aisle darker than the middle: the long battens get two, spread down the run.
    // Kept deliberately low. Five battens in a room seven metres by six all reach every wall,
    // and at the power a single pendant wants they sum into a white-out: the plaster and the
    // floor tile stop having any texture at all because everything has clipped. What is wanted
    // is the *direction* — brighter under the run than between the runs — not more light.
    const n = len > 3.2 ? 2 : 1;
    for (let i = 0; i < n; i++)
      B.light(cx + (n === 1 ? 0 : (i - .5) * len * .48), H - .26, cz,
        [1.00, 0.98, 0.93], .30, 2.5);
  }

  function build() {
    // ================================================================ shell
    // The floor is the one surface in here you cannot avoid looking at, and the whole reason a
    // 超市 sounds and feels the way it does: 45 cm porcelain floor tile, laid to the room. The
    // texture is read triplanar in world space. Tiles141 contains a 6×6 tile sheet and `matScale`
    // is metres per whole repeat, so 2.70 m makes the authored tiles 45 cm each. `matAmt` stays low
    // — the palette above was chosen
    // to sit *under* the goods, and the texture is here to give the fill a grain, not to
    // repaint the shop whatever colour the photograph happened to be.
    flat(0, 0, 0, RX * 2, RZ * 2, col.floor,
      { mode: 0, gloss: .30, mat: 'tile', matScale: 2.70, matAmt: .42 });
    // Ceiling: the floor quad turned over, the same way the apartment does it. Emissive, and so
    // deliberately bare — it is the light in this room, not a surface.
    B.props.push({ mesh: 'quad', color: col.ceil, mode: 1, alpha: 1,
      m: M.mul(M.trans(0, H, 0), M.mul(M.rotZ(Math.PI), M.scale(RX * 2, 1, RZ * 2))) });
    // Painted plaster on the three solid walls — at a 60 cm repeat, which is far tighter than a
    // plaster wants elsewhere in this game and is deliberate. The photograph is a trowelled
    // finish with swirls a good part of a metre across in its own frame: laid on at the two or
    // three metre repeat that suits a courtyard, one swirl comes out a metre and a half wide on
    // a 2.6 m wall and the shop looks like it has damp. Tightened to 60 cm the same swirls are
    // the size of a hand and do what a surface texture is for — they stop the fill being flat.
    const PLAS = { mat: 'plaster', matScale: .60, matAmt: .26 };
    wall(0, H / 2, RZ, RX * 2, H, Math.PI, col.wall, { mode: 4, ...PLAS });
    wall(-RX, H / 2, 0, RZ * 2, H, Math.PI / 2, col.wall, { mode: 4, ...PLAS });
    wall(RX, H / 2, 0, RZ * 2, H, -Math.PI / 2, col.wall, { mode: 4, ...PLAS });
    // The shopfront wall is mostly glass, so it comes as a frame rather than a plane: a stall
    // riser below the glazing, a header above it, and mullions between the panes.
    wall(0, H / 2, -RZ, RX * 2, H, 0, col.wall, { mode: 4, ...PLAS });
    // The riser under the glazing is tiled, the way every shopfront stallboard in the country
    // is, because it is the bit that gets kicked and hosed.
    box(0, .32, -RZ + .09, RX * 2, .64, .18, col.trim,
      { hard: true, gloss: G.paint, mat: 'tile', matScale: .30, matAmt: .32 });
    box(0, H - .22, -RZ + .09, RX * 2, .44, .18, col.wall,
      { hard: true, gloss: G.paint, ...PLAS });
    // Skirting, and the join where the wall meets the floor.
    for (const [x, z, sx, sz] of [[0, RZ - .04, RX * 2, .08], [-RX + .04, 0, .08, RZ * 2],
                                  [RX - .04, 0, .08, RZ * 2]])
      box(x, .06, z, sx, .12, sz, col.trim, { hard: true, gloss: G.paint });

    // ---- the glazing itself, and the door in it. Seen from inside, the alley beyond is a
    // pale slab: the street is a different scene and cannot be rendered through the glass, so
    // what stands in for it is a bright haze, which is what an overexposed shopfront looks
    // like from a dim interior anyway.
    for (const gx of [-2.55, -1.30, 1.30]) {
      box(gx, 1.44, -RZ + .06, 1.16, 1.60, .04, col.glass,
        { hard: true, mode: 1, alpha: .5, gloss: G.glass, glow: .30 });
      box(gx, 1.44, -RZ + .10, 1.16, 1.60, .02, col.white, { hard: true, mode: 1, glow: .22 });
    }
    for (const mx of [-3.15, -1.92, -.68, .70, 1.92, 3.15])
      box(mx, 1.42, -RZ + .10, .08, 1.68, .10, col.steel, { hard: true, gloss: G.metal });
    box(0, 2.26, -RZ + .10, RX * 2, .10, .12, col.steel, { hard: true, gloss: G.metal });

    // ---- 门 the way out. A glass door in an aluminium frame with a push bar, standing open.
    const dz = -RZ + .10;
    movingDoor(box(DX, 1.42, dz, 1.00, 1.90, .05, col.glass,
      { tag: '门', hard: true, mode: 1, alpha: .46, gloss: G.glass, glow: .34 }));
    movingDoor(box(DX, 1.42, dz + .03, 1.00, 1.90, .02, col.white,
      { tag: '门', hard: true, mode: 1, glow: .26 }));
    for (const [x, y, sx, sy] of [[DX - .49, 1.42, .09, 1.94], [DX + .49, 1.42, .09, 1.94],
                                  [DX, 2.40, 1.06, .09], [DX, .48, 1.06, .09]])
      movingDoor(box(x, y, dz + .04, sx, sy, .09, col.steel,
        { tag: '门', hard: true, gloss: G.metal }));
    movingDoor(capsule(DX - .30, 1.10, dz + .12, .028, .78, .028, col.steelD,
      { tag: '门', gloss: G.metal }));
    // 推 push / 拉 pull, the two characters on every shop door in the country.
    for(const g of glyphs(DX, 1.72, dz + .10, 0, '推',
      { size: .17, color: col.redD, mode: 1, lift: .02 })) movingDoor(g);
    // The way out knows where it comes out. Four interiors share the one 门 verb, so the
    // destination cannot live in the verb: it has to hang off the door itself.
    thing('门', DX, 2.14, dz + .30, '我买完了，出去吧。', "I'm done. Let's go out.",
      'The same 门 as your front door. Every way out of anywhere is one.',
      { focus: [DX, dz + 1.05], reach: 1.9 }).exit = { place: 'street', at: OUT };

    // ================================================================ 货架 the aisles
    // Two double-sided runs down the length of the shop with a walkway between them, and a
    // single run against the back wall. Anything wider and it stops being a corner shop.
    // Packaging colours, muted. At full saturation the two aisles came out as rows of sweets
    // and the shop read as a toy: real shelves are mostly red, cream and gold with the odd
    // blue or green among them, and the paper they are printed on is never that clean.
    // The former 4.60 m runs met the cold-case and till envelopes at their east ends. The rear
    // run actually overlapped the till collider by 0.57 m, turning the displays into two complete
    // barriers. A 3.80 m grocery run leaves 1.03 m beside the freezer; the compact 1.40 m impulse
    // run is centred west and leaves a 1.24 m queue route to the relocated compact till.
    gondola(-.35, -.15, 3.80, 0, '货架', ['dry', 'snack']);
    gondola(-1.80, 1.50, 1.40, 0, '货架', ['snack', 'dry']);
    thing('货架', -.35, 1.62, -.15, '方便面在第二个货架。',
      'The instant noodles are on the second shelf.',
      '货 goods + 架 rack. The word for any shelf in a shop.',
      { focus: [-.35, -.70], reach: 2.0 });

    // ---- 方便面 a wall of instant noodles at the end of the aisle, in stacked bowls and packs
    const nx = -2.90;
    box(nx, .80, 2.55, 1.30, 1.60, .40, col.steelD,
      { hard: true, gloss: G.metal, tag: '方便面',
        mat: 'metal', matScale: .30, matAmt: .26 });
    for (let d = 0; d < 4; d++) for (let i = 0; i < 4; i++) {
      const y = .30 + d * .36, x = nx - .48 + i * .32;
      cyl(x, y + .10, 2.42, .13, .20, pick([col.red, col.gold, col.orange, col.green]),
        { gloss: .26, tag: '方便面' });
      box(x, y + .225, 2.42, .28, .03, .28, col.white, { hard: true, gloss: .30, tag: '方便面' });
    }
    thing('方便面', nx, 1.76, 2.30, '一碗方便面三块五。', 'A pot of instant noodles is 3.5 kuai.',
      '方便 convenient + 面 noodles. The student staple, here as everywhere.',
      { focus: [nx, 1.85], reach: 1.9 });

    // ================================================================ 冰柜 the chest freezer
    // Against the +x wall, lid up, breathing cold. The glass lid and the ice-blue interior are
    // what make it read as refrigeration rather than a bench.
    // Seen from the side — which is how you see it walking in — a plain white box reads as a
    // counter, so the front gets a plinth, a livery band and its own character on it.
    // A shell again, for the third time in this room: plinth, a lower body, four walls above it
    // and an ice-blue liner floor they all stand on. Built as one 86 × 88 × 210 box — which it
    // was — the twelve boxes of dumplings were inside the solid volume of the carcass and the
    // chest read as an empty white bench with a sheet of glass on top.
    // Enamelled sheet, so it takes the same surface as the shelving at a finer repeat: a chest
    // freezer is a metre of white panel and without a grain on it it is a fridge-shaped fill.
    const FRIDGE = { mat: 'metal', matScale: .30, matAmt: .26 };
    const fx = RX - .52;
    box(fx, .08, -1.10, .90, .16, 2.14, col.steelD,
      { tag: '冰柜', hard: true, gloss: .30, ...FRIDGE });
    box(fx, .30, -1.10, .86, .28, 2.10, col.fridge, { tag: '冰柜', gloss: .34, ...FRIDGE });
    for (const [ox, oz, sx, sz] of [[-.40, 0, .06, 2.10], [.40, 0, .06, 2.10],
                                    [0, -1.02, .86, .06], [0, 1.02, .86, .06]])
      box(fx + ox, .66, -1.10 + oz, sx, .44, sz, col.fridge,
        { tag: '冰柜', gloss: .34, ...FRIDGE });
    box(fx, .46, -1.10, .74, .04, 1.98, C('#bcd9e4'),
      { tag: '冰柜', hard: true, gloss: .40 });
    box(fx - .44, .52, -1.10, .04, .26, 1.96, col.blue, { tag: '冰柜', hard: true, gloss: .30 });
    glyphs(fx - .46, .52, -1.70, -Math.PI / 2, '冷冻',
      { size: .17, gap: .05, color: col.white, mode: 1, tag: '冰柜', lift: .012 });
    // What is actually in it: bags of dumplings and 包子 standing on end in the near half, tubs of
    // ice cream in the far one. Twelve painted boxes in four random colours read as a crate of
    // building blocks, which is fair, because that is what they were.
    // Bags of dumplings and 包子 standing on end down the far half, tubs of ice cream stacked two
    // deep in the near half. Twelve painted boxes in four random colours read as a crate of
    // building blocks, which is fair, because that is what they were.
    for (let r = 0; r < 4; r++) for (const ox of [-.17, .17]) {
      const p = P[['dump', 'dump2', 'bao', 'dump'][r]];
      p.f(fx + ox, .535, -1.92 + r * .30, -Math.PI / 2 + (rnd() - .5) * .18,
        { tag: '冰柜' }, p.c);
    }
    for (let r = 0; r < 2; r++) for (const ox of [-.17, .17]) for (const ly of [.535, .672]) {
      const p = P[ly > .6 ? 'ice' : 'ice2'];
      p.f(fx + ox, ly, -.72 + r * .30, (rnd() - .5) * .5, { tag: '冰柜' }, p.c);
    }
    // The sliding glass lid, and it goes in *after* what is under it. Props are drawn in the
    // order they are built and a see-through one still writes depth, so the lid was cutting a
    // freezer-shaped hole in its own contents: twelve boxes of dumplings in there and the chest
    // read as an empty white bench with a sheet of glass on it.
    box(fx, .90, -1.10, .78, .05, 2.00, C('#9fc3d4'),
      { tag: '冰柜', hard: true, mode: 1, alpha: .14, glow: .04 });
    // The rim is a frame of four bars, not a lid. As one 90 × 216 slab of steel across the top
    // it sealed the freezer shut and everything inside it — the glass, the ice-blue lining and
    // eight boxes of dumplings — was under an opaque plate.
    for (const [ox, oz, sx, sz] of [[-.44, 0, .07, 2.16], [.44, 0, .07, 2.16],
                                    [0, -1.05, .90, .07], [0, 1.05, .90, .07]])
      box(fx + ox, 1.02, -1.10 + oz, sx, .12, sz, col.steel,
        { hard: true, gloss: G.metal, tag: '冰柜', ...FRIDGE });
    litten(box(fx - .355, .72, -1.10, .03, .26, 1.90, C('#cfe8f2'),
      { tag: '冰柜', hard: true, mode: 1, glow: .10 }), .5);
    // And the cold coming *out* of it. The strip above is an emissive sliver and the ice-blue
    // liner is a painted colour; neither of them puts a single photon on the bags of dumplings
    // standing in the well. One cold light down inside the chest, under the glass, does — and
    // it is the whole reason a freezer reads as refrigeration and not as a white bench: the
    // things in it are lit a different colour from the room they are standing in.
    B.light(fx - .10, .74, -1.10, [0.60, 0.83, 1.00], .46, 1.35);
    // And a few bags stood on the lid, because the inside of a chest freezer is below its own rim
    // and invisible from anywhere a person stands — and because every shop this size keeps the
    // overflow on top of it. Drawn after the glass and the rim so neither can cull them.
    for (const [ox, oz, kind] of [[-.16, -1.78, 'dump'], [.16, -1.74, 'bao'],
                                  [-.15, -1.44, 'dump2'], [.17, -1.40, 'dump']]) {
      const p = P[kind];
      p.f(fx + ox, .925, oz, -Math.PI / 2 + (rnd() - .5) * .30, { tag: '冰柜' }, p.c);
    }
    solid(fx - .48, RX, -2.20, .00);
    thing('冰柜', fx - .30, 1.30, -1.10, '冰柜里有冰淇淋和饺子。',
      'There is ice cream and dumplings in the freezer.',
      '冰 ice + 柜 cabinet. The chest kind; a fridge at home is a 冰箱.',
      { focus: [fx - 1.05, -1.10], reach: 1.9 });

    // ---- a drinks chiller beside it, upright, glass-fronted
    // A shell, like the gondolas: back, two ends, top, bottom and four decks, with the glass
    // door across the front. Built as one solid 74 × 184 × 160 carcass — which is what this
    // was — all twenty bottles stood inside the volume and the chiller was a blank white box.
    const dxr = RX - .46;
    box(dxr + .30, .92, 1.55, .14, 1.84, 1.60, col.fridge,
      { tag: '冰柜', gloss: .34, ...FRIDGE });
    for (const oz of [-.80, .80])
      box(dxr, .92, 1.55 + oz, .74, 1.84, .06, col.fridge,
        { tag: '冰柜', gloss: .34, ...FRIDGE });
    box(dxr, 1.80, 1.55, .74, .12, 1.60, col.fridge,
      { tag: '冰柜', gloss: .34, ...FRIDGE });
    box(dxr, .09, 1.55, .74, .18, 1.60, col.steelD,
      { tag: '冰柜', hard: true, gloss: G.metal, ...FRIDGE });
    // Four decks of drinks behind the glass, faced up by kind: water and cola at the bottom where
    // the cases go, beer above it, the dairy at the top. Turned a quarter so every printed label
    // faces out through the door rather than along the shelf.
    const CHILL = [['water', 'water', 'cola', 'cola', 'water'],
                   ['beer', 'beer', 'cola', 'water', 'beer'],
                   ['milk', 'milk', 'juice', 'yog', 'milk'],
                   ['juice', 'yog', 'water', 'cola', 'juice']];
    for (let d = 0; d < 4; d++) {
      box(dxr + .04, .38 + d * .38, 1.55, .60, .025, 1.46, col.chrome,
        { tag: '冰柜', hard: true, gloss: G.metal, mat: 'metal', matScale: .28, matAmt: .24 });
      for (let i = 0; i < 5; i++) {
        const p = P[CHILL[d][i]];
        p.f(dxr + .02, .40 + d * .38, .96 + i * .30, -Math.PI / 2, { tag: '冰柜' }, p.c);
      }
    }
    box(dxr - .34, 1.00, 1.55, .06, 1.50, 1.34, col.glass,
      { tag: '冰柜', hard: true, mode: 1, alpha: .40, gloss: G.glass });
    box(dxr - .35, 1.00, .90, .07, 1.54, .07, col.steel,
      { tag: '冰柜', hard: true, gloss: G.metal });
    box(dxr - .35, 1.00, 2.20, .07, 1.54, .07, col.steel,
      { tag: '冰柜', hard: true, gloss: G.metal });
    capsule(dxr - .40, 1.00, 2.06, .022, .60, .022, col.steelD,
      { tag: '冰柜', gloss: G.metal });
    litten(box(dxr - .28, 1.72, 1.55, .04, .06, 1.30, col.tube,
      { tag: '冰柜', hard: true, mode: 1, glow: .34 }), .8);
    // The chiller's own light, cold, behind the glass and above the top deck where the real
    // strip is. This is the one lamp in the shop that is a different colour temperature from
    // everything else, and it is what makes a glass-fronted case read as cold from across the
    // room — the bottles behind the door come out blue while the shelf beside them stays white.
    B.light(dxr - .06, 1.62, 1.55, [0.62, 0.84, 1.00], .52, 1.55);
    solid(dxr - .40, RX, .70, 2.40);

    // ================================================================ 水果 produce, by the window
    // Angled crates on a trestle, which is how fruit is always shown: tipped toward you.
    const px = -2.45;
    // Six crates: oranges, apples and pears in the front row, and behind them the greens a
    // Chinese greengrocer always has out — a 白菜 or two and a bundle of spring onions. Six balls
    // in three colours is a bowl of marbles; the silhouette is what tells you what a vegetable is.
    const CRATE = [['ball', col.orange, .095], ['ball', C('#b03a2c'), .082],
                   ['ball', C('#c6c268'), .086], ['cabbage'],
                   ['ball', C('#c4402f'), .072], ['scallion']];
    for (const s of [0, 1]) {
      const cz = -2.10 + s * .78;
      box(px, .34, cz, 1.70, .10, .70, col.woodD,
        { hard: true, rx: -.16, gloss: G.wood, mat: 'wood', matScale: .70, matAmt: .42 });
      for (const [ox, col3] of [[-.55, 0], [0, 1], [.55, 2]]) {
        const spec = CRATE[s * 3 + col3];
        box(px + ox, .46, cz, .52, .22, .62, col.card,
          { hard: true, rx: -.16, gloss: .18, tag: '水果' });
        // The crate is a solid box up to .57, so everything in it stands *on* .57. Placed by eye
        // instead, six apples at y .60 are six apples buried to the waist in a cream slab, which
        // is what a crate of half-domes looks like from the aisle: marbles pressed into putty.
        if (spec[0] === 'ball') {
          for (let i = 0; i < 6; i++)
            ball(px + ox - .16 + (i % 3) * .16, .585 + spec[2] * .9 + ((i / 3) | 0) * .022,
              cz - .12 + ((i / 3) | 0) * .22, spec[2], spec[2] * .9, spec[2],
              spec[1], { gloss: .30, tag: '水果' });
        } else if (spec[0] === 'cabbage') {
          // 白菜 pale and oval standing on end, in a collar of darker outer leaf.
          for (let i = 0; i < 3; i++) {
            const bx = px + ox - .15 + i * .15, bz = cz - .06 + (i % 2) * .16;
            ball(bx, .725, bz, .085, .125, .085, C('#e2e6c4'), { gloss: .22, tag: '水果' });
            ball(bx, .655, bz, .098, .070, .098, C('#7f9a52'), { gloss: .26, tag: '水果' });
          }
        } else {
          // 葱 a bundle of spring onions lying across the crate, white ends toward you.
          for (let i = 0; i < 5; i++) {
            const bx = px + ox - .18 + i * .09, a = .30 + (rnd() - .5) * .12;
            capsule(bx, .60, cz + .10, .016, .17, .016,
              C('#eae7dc'), { rx: 1.35, ry: a, gloss: .24, tag: '水果' });
            capsule(bx, .63, cz - .13, .015, .30, .015,
              C('#5f8f43'), { rx: 1.35, ry: a, gloss: .24, tag: '水果' });
          }
        }
      }
    }
    for (const ox of [-.7, .7]) for (const oz of [-2.35, -1.05])
      capsule(px + ox, .18, oz, .03, .36, .03, col.steelD, { gloss: G.metal });

    // 称重 — the scale the purchase line has always claimed the cashier shows you. It stands over
    // the narrow gap between the two crate rows, wholly inside the fruit stand's existing solid,
    // so making that line visible adds no blocker and cannot narrow the aisle. The display is an
    // opaque seven-segment 0.5 rather than glyph atlas cells: ordinary boxes keep the complete
    // fixture in the renderer's plain mode-0 stream and 0.5 kg is exactly one 斤.
    const sx = -1.73, sz = -1.70, sy = 1.22;
    const SCALE = { tag:'称重', hard:true, bevel:0 };
    box(sx, .55, sz, .34, .10, .12, col.steelD, { ...SCALE, gloss:G.metal });
    box(sx, .86, sz - .02, .035, .62, .035, col.steelD, { ...SCALE, gloss:G.metal });
    box(sx, .88, sz + .04, .18, .12, .14, col.steelD, { ...SCALE, gloss:G.metal });
    box(sx, .95, sz + .04, .42, .035, .28, col.steel, { ...SCALE, gloss:.42 });
    box(sx, sy, sz, .36, .24, .10, col.fridge, { ...SCALE, gloss:.28 });
    box(sx, sy, sz + .056, .30, .17, .012, col.charcoal, { ...SCALE, gloss:.18 });
    const faceZ = sz + .066;
    const segment = (x, y, w, h) =>
      box(x, y, faceZ, w, h, .008, col.lime, { ...SCALE, gloss:.24 });
    const digit = (x, on) => {
      if (on.includes('a')) segment(x, sy + .061, .052, .010);
      if (on.includes('b')) segment(x + .032, sy + .031, .010, .050);
      if (on.includes('c')) segment(x + .032, sy - .031, .010, .050);
      if (on.includes('d')) segment(x, sy - .061, .052, .010);
      if (on.includes('e')) segment(x - .032, sy - .031, .010, .050);
      if (on.includes('f')) segment(x - .032, sy + .031, .010, .050);
      if (on.includes('g')) segment(x, sy, .052, .010);
    };
    digit(sx - .070, 'abcdef');
    segment(sx, sy - .056, .012, .012);
    digit(sx + .070, 'afgcd');

    solid(px - .95, px + .95, -2.55, -.85);
    thing('水果', px, .92, -1.70, '水果多少钱一斤？', 'How much is the fruit per jin?',
      '水 water + 果 fruit. Sold by the 斤 — half a kilo.',
      { focus: [px, -.55], reach: 2.0 });

    // ---- 米 sacks of rice on the floor at the end, because they always are
    // Woven sacks with a printed panel on the aisle face of each. Three plain cream pillows
    // stacked up read as three pillows; a darker band *round* the middle of each was worse —
    // it read as a filling and the stack came out as a plate of sandwiches.
    for (let i = 0; i < 3; i++) {
      const sx3 = -3.10 + i * .04, sy3 = .22 + i * .30, sz3 = .55 + i * .02;
      const syaw = .10 - i * .09;
      box(sx3, sy3, sz3, .78, .34, .54, col.cream,
        { tag: '米', gloss: .14, ry: syaw, round: .07,
          mat: 'fabric', matScale: .26, matAmt: .34 });
      // .385 straddles the face of a 78 cm sack. At .37 the panel was 4 cm inside it.
      box(sx3 + .385 * Math.cos(syaw), sy3, sz3 - .385 * Math.sin(syaw), .03, .17, .34, col.red,
        { tag: '米', hard: true, gloss: .18, ry: syaw });
    }
    // and the character on the aisle face too — you come at these from +x, not the wall side
    glyphs(-3.06 + .385, .52, .57, Math.PI / 2, '米',
      { size: .14, color: col.goldL, mode: 1, lift: .03, tag: '米' });
    // Printed on the front of the bottom sack. yaw 0 faces +z, so on a -z face it has to be
    // Math.PI — written the other way round the character sits a centimetre *inside* the sack
    // and never draws at all.
    glyphs(-3.06, .52, .28, Math.PI, '米', { size: .20, color: col.redD, lift: .01, tag: '米' });
    solid(-RX, -2.60, .20, .95);
    thing('米', -3.06, 1.00, .55, '买一袋米吧。', "Let's buy a bag of rice.",
      '米 is uncooked rice; cooked, in a bowl, it is 饭.',
      { focus: [-2.30, .55], reach: 1.9 });

    // ================================================================ 收银台 the till
    // The compact counter sits beyond the main aisle, facing the entrance. Moving it 1.30 m west
    // and 20 cm north removes its former 0.48 x 1.22 m physical overlap with the drinks chiller;
    // shortening it keeps a 0.96 m clear bay to that case and 1.24 m to the impulse shelf.
    const tx = 1.00, tz = 1.55;
    box(tx, .48, tz, 1.40, .96, .74, col.lino,
      { tag: '收银台', gloss: .26, mat: 'plaster', matScale: .55, matAmt: .24 });
    box(tx, .98, tz, 1.48, .06, .82, col.woodD,
      { tag: '收银台', hard: true, gloss: G.wood, mat: 'wood', matScale: .85, matAmt: .42 });
    // The front of the counter carries the shop's name, the way they all do. In near-black it
    // was a 1.7 metre hole in the middle of the room.
    box(tx, .52, tz - .40, 1.40, .70, .04, col.blue,
      { tag: '收银台', hard: true, gloss: .20 });
    box(tx, .78, tz - .41, 1.40, .06, .03, col.goldL,
      { tag: '收银台', hard: true, mode: 1 });
    glyphs(tx, .52, tz - .42, Math.PI, '幸福超市',
      { size: .17, gap: .07, color: col.white, mode: 1, tag: '收银台' });
    // The till itself, a card reader on a stand, and a jar of lighters by the hand.
    box(tx + .48, 1.13, tz + .06, .44, .24, .40, col.white, { tag: '收银台', gloss: .30 });
    box(tx + .48, 1.24, tz - .10, .34, .10, .16, col.charcoal,
      { tag: '收银台', hard: true, mode: 1, glow: .10 });
    litten(box(tx + .48, 1.245, tz - .11, .28, .07, .02, C('#8fe0b0'),
      { tag: '收银台', hard: true, mode: 1, glow: .30 }), .6);
    capsule(tx - .28, 1.12, tz - .16, .022, .26, .022, col.steelD, { gloss: G.metal });
    box(tx - .28, 1.30, tz - .16, .16, .22, .04, col.charcoal,
      { tag: '收银台', hard: true, gloss: .40 });
    // Lighters in the jar before the jar, for the same reason as the freezer lid.
    for (let i = 0; i < 5; i++)
      box(tx - .62 + (i % 3) * .04, 1.08, tz + .02 + (i - 2) * .012, .014, .10, .014,
        pick([col.red, col.blue, col.yellow]), { hard: true, tag: '收银台' });
    cyl(tx - .60, 1.08, tz + .02, .07, .14, col.glass,
      { tag: '收银台', mode: 1, alpha: .5, gloss: G.glass });
    // A stool behind it, pushed to the far end so the working position stays clear.
    taper(tx - .66, .22, tz + .52, .32, .44, .32, col.steelD, { gloss: G.metal });
    box(tx - .66, .45, tz + .52, .34, .05, .34, col.charcoal, { gloss: .22 });
    const scx = tx - .66, scz = tz + .52;
    box(scx, .70, scz, .055, .32, .30, col.charcoal, { hard: true, mode: 1, alpha: .86 });
    [-1, 1].forEach(s => ball(scx, .86, scz + s * .14, .025, .075, .085, col.charcoal, { mode: 1, alpha: .86 }));
    capsule(scx, .94, scz, .024, .085, .040, col.charcoal, { mode: 1, alpha: .86 });
    ball(scx, 1.06, scz, .030, .105, .095, col.charcoal, { mode: 1, alpha: .88 });
    for (let i = 0; i < 4; i++)
      box(tx + .74, .78 - i * .015, tz + .30, .20, .28, .02 + i * .005, col.white,
        { hard: true, alpha: .8, gloss: .40, ry: (i - 1.5) * .06 });
    solid(tx - .84, tx + .78, tz - .44, tz + .68);
    shade(tx, tz, 2.0, 1.2, .32);
    thing('收银台', tx, 1.44, tz - .38, '在收银台交钱。', 'You pay at the till.',
      '收 collect + 银 silver + 台 counter. 交钱 or 付钱 is to hand the money over.',
      { focus: [tx, tz - 1.15], reach: 1.9 });

    // 购物篮 a stack of baskets by the door, where you pick one up on the way in
    // Nested, with a rim and a hollow you can see into on the top one. Four solid boxes stacked
    // 11 cm apart read as a single orange block with a bar across it.
    for (let i = 0; i < 4; i++) {
      const y = .09 + i * .105, r = (i % 2) * .06;
      box(1.05, y, -1.95, .42, .17, .30, col.red, { tag: '购物篮', gloss: .30, ry: r });
      box(1.05, y + .095, -1.95, .44, .035, .32, col.redD,
        { tag: '购物篮', hard: true, gloss: .34, ry: r });
      capsule(1.05, y + .17, -1.95, .020, .30, .020, col.charcoal,
        { tag: '购物篮', rz: Math.PI / 2, gloss: .30, ry: r });
    }
    box(1.05, .49, -1.95, .34, .04, .24, col.floor, { tag: '购物篮', hard: true, gloss: .20 });
    thing('购物篮', 1.05, .62, -1.95, '拿一个购物篮。', 'Take a basket.',
      '购物 shopping + 篮 basket. 买东西 is the everyday way to say it.',
      { focus: [1.05, -1.25], reach: 1.7 });

    // ================================================================ signage and lighting
    // A price banner over the aisles and a hanging sign over the till: both are how a Chinese
    // supermarket tells you where anything is.
    // Both are printed on both faces. Hung across a room, a banner lettered on one side only
    // is a blank board to half the people in it, and the half that got the blank side was the
    // half walking in through the door.
    box(-.35, 2.24, -1.05, 3.20, .30, .04, col.red, { hard: true, gloss: .18 });
    glyphs(-.35, 2.24, -1.03, 0, '天天低价', { size: .21, gap: .08, color: col.goldL, mode: 1 });
    glyphs(-.35, 2.24, -1.07, Math.PI, '天天低价',
      { size: .21, gap: .08, color: col.goldL, mode: 1 });
    // And a thing on it, which is what makes the words on it teachable.
    //
    // Glyphs are geometry. A word painted on a board is read by the player and not by the game: the
    // dictionary is only ever consulted through a thing you walked up to, so 天天低价 hung over the
    // middle of the shop in gold letters for as long as this room has existed and there was no way
    // to ask what it said. A dictionary row for it would have been unreachable too — the word card
    // only opens off a thing. This is the smallest possible fix and it turns four characters of
    // scenery into four characters of vocabulary.
    //
    // The focus is out in the aisle rather than under the banner: it hangs at 2.24 m across the
    // middle of the floor, and a spot directly beneath it is a spot where you cannot see it.
    thing('天天低价', -.35, 2.24, -1.05, '天天低价，就是每天都便宜。',
      "Low prices every day — that is what the banner over the aisles says.",
      '天天 every day + 低 low + 价 price. Shops put it up whether it is true or not.',
      { focus: [-.35, .55], reach: 2.6 });
    box(tx, 2.20, tz - .50, 1.32, .34, .05, col.blue, { hard: true, gloss: .24 });
    glyphs(tx, 2.20, tz - .525, Math.PI, '收银', { size: .22, gap: .10, color: col.white, mode: 1 });
    glyphs(tx, 2.20, tz - .475, 0, '收银', { size: .22, gap: .10, color: col.white, mode: 1 });
    for (const s of [-1, 1])
      capsule(tx + s * .52, 2.42, tz - .50, .012, .38, .012, col.steelD, { gloss: G.metal });

    tube(-1.20, -1.00, 4.20);
    tube(-1.20, 1.90, 4.20);
    tube(2.40, .40, 2.60);

    // ---- 空调 a wall unit over the door, and the plastic strip curtain under it
    box(-2.10, 2.28, RZ - .18, 1.00, .32, .26, col.white, { tag: '空调', gloss: .27 });
    box(-2.10, 2.16, RZ - .30, .88, .05, .06, C('#c9c8c3'), { tag: '空调', hard: true });
    thing('空调', -2.10, 2.52, RZ - .34, '空调开得很足。', 'The air conditioning is on full.',
      'Every shop in a Beijing summer keeps the door open and the AC running.',
      { focus: [-2.10, RZ - 1.30], reach: 1.9 });

    // a mop and bucket in the corner, and a stack of crates: the back-of-shop clutter
    capsule(-3.30, .62, 2.60, .028, 1.24, .028, col.wood, { rz: .16, gloss: G.wood });
    box(-3.22, .06, 2.66, .26, .12, .18, col.steelD, { hard: true, gloss: G.metal, rz: .16 });
    cyl(-2.95, .16, 2.70, .19, .32, col.blue, { gloss: .32 });
    for (let i = 0; i < 3; i++)
      box(3.10, .14 + i * .28, 2.60, .58, .26, .48, pick([col.blue, col.red, col.jade]),
        { hard: true, gloss: .28, ry: (rnd() - .5) * .12 });

    // ================================================================ ambiance
    // The things that are in every one of these shops and that nobody puts in a model of one:
    // bunting nobody has taken down since new year, a security mirror in the corner, arrows on
    // the floor, a fan zip-tied to a shelf upright, the radio behind the till, and a promotional
    // standee left where it blocks the aisle.

    // ---- 三角旗 bunting, strung corner to corner over the aisles
    for (const [ax, az, bx, bz] of [[-RX + .3, -2.2, RX - .3, -.2], [-RX + .3, 2.6, RX - .3, .6]]) {
      const n = 11, dx = (bx - ax) / n, dz = (bz - az) / n;
      for (let i = 0; i <= n; i++) {
        const t = i / n, sag = Math.sin(t * Math.PI) * .13;
        const x = ax + dx * i, z = az + dz * i, y = H - .30 - sag;
        // 10 mm of pale cord, not 6 mm of charcoal: at a millimetre on screen and near-black
        // the spans read as hairline scratches across the ceiling rather than string.
        capsule(x, y, z, .010, Math.hypot(dx, dz) * 1.02, .010, col.trim,
          { rz: Math.PI / 2, ry: Math.atan2(dx, dz) + Math.PI / 2, gloss: .20 });
        if (i === n) continue;
        // a triangular pennant hanging off each span, alternating red and gold
        taper(x + dx / 2, y - .11, z + dz / 2, .16, .20, .02,
          i % 2 ? col.goldL : col.red,
          { mode: 7, gloss: G.fabric, rx: Math.PI, ry: Math.atan2(dx, dz) });
      }
    }

    // ---- 凸面镜 the convex security mirror, high in the far corner where it sees both aisles
    const mrx = -RX + .30, mrz = RZ - .30;
    box(mrx + .10, 2.20, mrz - .10, .22, .06, .22, col.steelD, { hard: true, gloss: G.metal });
    // One lit dome at a low gloss. Two spheres, a dark housing with a pale one inside it, gave
    // a black disc with a white crescent showing round the edge; and at gloss .72 the specular
    // on a twenty-segment ball is faceted, which looked like a crack across the glass.
    ball(mrx + .28, 2.10, mrz - .28, .245, .245, .245, C('#c6d1d8'), { gloss: .22 });

    // ---- arrows and a warning on the floor: the yellow paint every shop floor has
    for (let i = 0; i < 3; i++) {
      const az2 = -1.9 + i * 1.5;
      flat(1.55, .006, az2, .34, .06, col.yellow, { gloss: .12 });
      for (const t of [-1, 1])
        flat(1.68, .006, az2 + t * .09, .16, .06, col.yellow, { gloss: .12, ry: t * .8 });
    }
    // The painted lane the arrows run down. It takes the same tile at the same size as the
    // floor it is painted on, or it reads as a sheet of lino laid over the tiling.
    flat(1.55, .005, .60, .70, 2.90, C('#c9c2ac'),
      { mode: 0, gloss: .14, mat: 'tile', matScale: 2.70, matAmt: .24 });

    // ---- a clip fan on the end of the first aisle, and the radio behind the till
    // Clamped to the top of the gondola upright — visibly clamped. With nothing but a 30 cm
    // stem it hung in the air beside the shelf with no explanation.
    // Clamped to the far upright, not the one by the till: at x 1.95 it sat directly behind the
    // cashier's head from every angle you actually see her from, and read as a halo.
    const fnx = -2.65, fnz = -.16;
    box(fnx, 1.55, fnz, .11, .13, .17, col.charcoal, { hard: true, gloss: .34 });
    box(fnx, 1.47, fnz - .04, .075, .12, .10, col.charcoal, { hard: true, gloss: .34 });
    capsule(fnx, 1.72, fnz, .020, .26, .020, col.steelD, { gloss: G.metal });
    cyl(fnx, 1.86, fnz + .08, .055, .13, col.charcoal, { rx: Math.PI / 2, gloss: .40 });
    cyl(fnx, 1.86, fnz, .075, .08, col.steelD, { rx: Math.PI / 2, gloss: G.metal });
    for (let i = 0; i < 3; i++) {
      const p=box(fnx, 1.86, fnz - .02, .055, .27, .05, col.trim,
        { hard: true, gloss: .30, rz: i * 2.09, ry: .20 });
      fanBlades.push({p,m0:new Float32Array(p.m)});
    }
    // The guard: a rim of short bars, eight radials and one hazy disc for the mesh. Built as
    // six filled discs of falling radius at a single z it came out as a bullseye, and the fan
    // read as a dartboard.
    for (let i = 0; i < 14; i++) {
      const a = i * Math.PI * 2 / 14;
      box(fnx + Math.cos(a) * .165, 1.86 + Math.sin(a) * .165, fnz - .075,
        .015, .078, .015, col.steel, { hard: true, gloss: G.metal, rz: a });
    }
    // Rim only. Radials across a guard this size read as spokes at any distance, and with a
    // translucent plate behind them as well the thing was a bicycle wheel bolted to a shelf.
    box(tx + .82, 1.09, tz + .10, .26, .14, .18, col.charcoal, { gloss: .30 });
    for (let i = 0; i < 4; i++)
      box(tx + .82, 1.09, tz + .01, .04, .10, .01, col.steelD, { hard: true, ry: i * .4 });
    litten(box(tx + .82, 1.15, tz + .01, .10, .02, .01, C('#8fd0e0'),
      { hard: true, mode: 1, glow: .24 }), .5);

    // ---- 特价 a promotional standee by the aisle mouth, half in the way
    // Not at x 1.05: that is where the baskets are, and from the door the two stood one behind
    // the other and read as a single red slab a metre and a half tall with a label on it.
    //
    // The writing is placed at the *centre* of the panel and stood off with `lift`, not moved
    // in world z. The panel is turned 0.22 rad; a row of characters laid out at a fixed world z
    // cuts through a turned panel, and half of 特价 was inside the board.
    const stx = -.20, stz = -2.05;
    taper(stx, .05, stz, .46, .10, .40, col.charcoal, { gloss: .26 });
    box(stx, .72, stz, .52, 1.28, .05, col.red, { hard: true, gloss: .24, ry: .22 });
    // A white panel under the price. Nearly a metre and a half of unbroken red read as a door
    // leaning against the shelves rather than a card standee.
    box(stx, .30, stz, .46, .38, .06, col.white, { hard: true, gloss: .22, ry: .22 });
    // Math.PI + the panel's own turn, so the printed side faces the door. At yaw .22 the two
    // lines were stood off on the +z side and pointed at the back wall, and everyone coming in
    // saw the blank back of a red board.
    glyphs(stx, 1.02, stz, Math.PI + .22, '特价',
      { size: .21, gap: .06, color: col.goldL, mode: 1, lift: .045 });
    // Three characters at .24 with a .03 gap span 78 cm across a 52 cm board, so both nines
    // hung off the sides of it in mid-air.
    glyphs(stx, .32, stz, Math.PI + .22, '9.9',
      { size: .17, gap: -.045, color: col.redD, mode: 1, lift: .05 });
    capsule(stx + .02, .40, stz + .16, .020, .70, .020, col.steelD, { gloss: G.metal, rx: .22 });
    solid(stx - .30, stx + .30, stz - .26, stz + .26);

    // ---- price stickers on the shopfront glass, seen back-to-front from in here
    for (const [gx, txt] of [[-2.55, '鸡蛋'], [-1.30, '啤酒']])
      glyphs(gx, 1.86, -RZ + .13, 0, txt,
        { size: .16, gap: .05, color: col.red, mode: 1, alpha: .8 });

    // ---- a pallet of boxes and a sack trolley behind the aisles, mid-restock
    // Not at x 2.95, z 1.05: the whole +x wall is refrigeration, and a pallet there stood with
    // half of it inside the end of the till counter. Behind the second run of shelving is the
    // one bit of floor in the shop nothing else wants.
    const plx = -1.30, plz = 2.45;
    for (let i = 0; i < 5; i++)
      box(plx + (i % 2) * .06, .18 + ((i / 2) | 0) * .34, plz, .58, .32, .44,
        i % 2 ? col.card : col.cardD, { hard: true, gloss: .16, ry: (rnd() - .5) * .14,
          mat: 'plaster', matScale: .30, matAmt: .26 });
    box(plx, .02, plz, .74, .06, .60, col.woodD,
      { hard: true, gloss: G.wood, mat: 'wood', matScale: .60, matAmt: .44 });
    capsule(plx - .62, .52, plz - .10, .022, 1.00, .022, col.steelD,
      { gloss: G.metal, rx: -.22 });
    capsule(plx - .46, .52, plz - .06, .022, 1.00, .022, col.steelD,
      { gloss: G.metal, rx: -.22 });
    box(plx - .54, .04, plz - .33, .34, .05, .30, col.steelD, { hard: true, gloss: G.metal });
    solid(plx - .70, plx + .42, plz - .40, plz + .35);

    // ---- the cold coming off the chiller: a pool of blue on the floor in front of it, which is
    // the one thing a lit glass door actually does to a room
    glow(M.trs(dxr - .70, .02, 1.55, 0, 1.5, 1, 2.0), C('#8fd8f0'), .10);
    for (let i = 0; i < 5; i++)
      box(dxr - .35, .55 + i * .30, 1.10 + (i % 2) * .90, .01, .10, .34, C('#dff1f8'),
        { hard: true, mode: 1, alpha: .22, glow: .04 });

    // ---- 价格 a price ticket on every fixture you can buy from, printed off the GOODS list.
    // A shop where nothing has a price on it is a museum, and the number has to be on the
    // shelf as well as in the code or there is no way to know what you are agreeing to.
    for (const g of GOODS) {
      const [tx2, ty2, tz2] = g.at;
      if (g.spike)
        capsule(tx2, ty2 - g.spike / 2 - .04, tz2, .008, g.spike, .008, col.steelD,
          { tag: g.hz, gloss: G.metal });
      box(tx2, ty2, tz2, .19, .11, .012, col.white,
        { tag: g.hz, hard: true, gloss: .22, ry: g.yaw });
      box(tx2, ty2 + .048, tz2, .19, .018, .014, col.yellow,
        { tag: g.hz, hard: true, mode: 1, ry: g.yaw });
      // Negative gap. Every glyph is drawn in a square cell and the ink in a Latin one fills
      // about half of it, so at the same spacing as a 汉字 "¥20" read as three separate marks
      // rather than as a price.
      // 起 — "from". A gondola holds ten things at ten prices and one number on it would be a
      // lie about nine of them, so the two open fixtures quote their cheapest line the way a
      // real shelf edge does.
      glyphs(tx2, ty2 - .008, tz2, g.yaw, '¥' + g.price + (g.from ? '起' : ''),
        { size: .058, gap: -.018, color: col.redD, mode: 1, lift: .012, tag: g.hz });
    }

    // and the floor tiles' expansion joints, which is what makes a tiled floor read as tiled
    for (let i = -3; i <= 3; i++)
      flat(i * 1.05, .004, 0, .03, RZ * 2, col.grout, { gloss: .10 });
  }

  build();

  // Fluorescent tubes do not care what time it is, but the daylight through the shopfront
  // does, so the tubes are worth a little more once the alley outside has gone dark.
  function setNight(k) {
    const soft = k * k * (3 - 2 * k);
    for (const { p, k: kk } of litProps)
      p.glow = (p.glow0 === undefined ? (p.glow0 = p.glow || 0) : p.glow0) + soft * kk * .22;
  }

  // Apply a world-space hinge turn to a captured rest matrix without allocating per frame.
  function hingePart(q, px, pz, a) {
    const p=q.p,m=p.m,b=q.m0,c=Math.cos(a),s=Math.sin(a);
    for(let j=0;j<3;j++) {
      const o=j*4,x=b[o],z=b[o+2];
      m[o]=c*x+s*z; m[o+1]=b[o+1]; m[o+2]=-s*x+c*z; m[o+3]=b[o+3];
    }
    const dx=b[12]-px,dz=b[14]-pz;
    m[12]=px+c*dx+s*dz; m[13]=b[13]; m[14]=pz-s*dx+c*dz; m[15]=1;
    p.cx=m[12]; p.cy=m[13]; p.cz=m[14];
    if(q.ob) {
      const ox=q.ob.x-px,oz=q.ob.z-pz;
      p.ob.x=px+c*ox+s*oz; p.ob.z=pz-s*ox+c*oz; p.ob.ry=q.ob.ry+a;
    }
  }

  function tick(t,body) {
    const dx=body?body.x-DX:99,dz=body?body.z-(-RZ+.65):99;
    let open=1-Math.min(1,Math.hypot(dx,dz)/1.75);
    open=open*open*(3-2*open);
    const angle=1.20*open, hx=DX+.53, hz=-RZ+.10;
    for(let i=0;i<doorParts.length;i++) hingePart(doorParts[i],hx,hz,angle);

    // The blade rest matrices already include their slight pitch. A world-Z spin preserves it
    // while making the little clip fan visibly work.
    const a=t*7.2,c=Math.cos(a),s=Math.sin(a),px=-2.65,py=1.86;
    for(let i=0;i<fanBlades.length;i++) {
      const q=fanBlades[i],p=q.p,m=p.m,b=q.m0;
      for(let j=0;j<3;j++) {
        const o=j*4,x=b[o],y=b[o+1];
        m[o]=c*x-s*y; m[o+1]=s*x+c*y; m[o+2]=b[o+2]; m[o+3]=b[o+3];
      }
      const x=b[12]-px,y=b[13]-py;
      m[12]=px+c*x-s*y; m[13]=py+s*x+c*y; m[14]=b[14]; m[15]=1;
    }
  }

  return B.finish({
    setNight, tick, GOODS, SHELF, RX, RZ, H, WIN, OUT,
    label: '超市', labelK: '超市 · shop',
    indoor: true, cutaway: true, near: .05, far: 40, expose: 1,
    // Just inside the door, looking down the aisle.
    spawn: { x: DX - .35, z: -RZ + .95, yaw: Math.PI * .06 },
    zones: [{ id: 'shop', x0: -RX, x1: RX, z0: -RZ, z1: RZ, light: [0, H - .30, .40] }],
    roomAt() { return this.zones[0]; },
  });
});
