#!/usr/bin/env python3
"""Generate deterministic neutral GNM Asian-category head studies.

This is an offline authoring utility. It intentionally writes into ``.cache``
by default and does not modify game/runtime assets. GNM's semantic label is the
broad ``ASIAN`` class; the output must not be presented as a Chinese-ethnicity
classifier or as evidence of any individual's ethnicity.

Run with the isolated environment created for GNM::

  .cache/gnm-venv/bin/python \
    tools/characters/generate_gnm_asian_heads.py
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import subprocess
from typing import Iterable

import numpy as np
from gnm.shape import gnm_numpy
from gnm.shape import semantic_sampler


DEFAULT_SEEDS = (7, 19, 31, 43, 59, 83)
COMPONENT_GROUPS = {
    # Keep internal mouth-sock geometry out of the neutral clay study; it can
    # become visible through the exterior at some camera angles and distract
    # from the facial silhouette.
    "skin": "skin_exterior",
    "scleras": "scleras",
    "irises": "irises",
    "pupils": "pupils",
}


def _parse_args() -> argparse.Namespace:
  parser = argparse.ArgumentParser(description=__doc__)
  parser.add_argument(
      "--output",
      type=Path,
      default=Path(".cache/gnm-asian-samples"),
      help="Output directory (default: .cache/gnm-asian-samples).",
  )
  parser.add_argument(
      "--seeds",
      type=int,
      nargs="+",
      default=list(DEFAULT_SEEDS),
      help="Deterministic latent seeds to generate for each gender.",
  )
  parser.add_argument(
      "--gnm-source",
      type=Path,
      default=Path(".cache/gnm-src"),
      help="GNM source checkout, used only to record its revision.",
  )
  return parser.parse_args()


def _git_revision(source: Path) -> str | None:
  try:
    return subprocess.run(
        ["git", "-C", str(source), "rev-parse", "HEAD"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()
  except (OSError, subprocess.CalledProcessError):
    return None


def _group_face_mask(
    model: gnm_numpy.GNM,
    group_name: str,
) -> np.ndarray:
  names = [str(name) for name in model.vertex_group_names]
  try:
    group_index = names.index(group_name)
  except ValueError as exc:
    raise ValueError(f"GNM vertex group is missing: {group_name}") from exc
  vertex_mask = np.asarray(model.vertex_groups[group_index]) > 0.5
  return np.all(vertex_mask[np.asarray(model.triangles)], axis=1)


def _write_obj(
    path: Path,
    vertices: np.ndarray,
    triangles: np.ndarray,
    face_mask: np.ndarray,
    object_name: str,
) -> dict[str, int]:
  """Write one compact triangle-only OBJ and return geometry counts."""
  selected_faces = np.asarray(triangles)[face_mask]
  used_vertices = np.unique(selected_faces.reshape(-1))
  remap = np.full(len(vertices), -1, dtype=np.int64)
  remap[used_vertices] = np.arange(len(used_vertices), dtype=np.int64)
  compact_faces = remap[selected_faces]
  compact_vertices = np.asarray(vertices)[used_vertices]

  path.parent.mkdir(parents=True, exist_ok=True)
  with path.open("w", encoding="utf-8", newline="\n") as stream:
    stream.write("# Generated by generate_gnm_asian_heads.py\n")
    stream.write(f"o {object_name}\n")
    for x, y, z in compact_vertices:
      stream.write(f"v {x:.9f} {y:.9f} {z:.9f}\n")
    for a, b, c in compact_faces + 1:
      stream.write(f"f {a} {b} {c}\n")
  return {
      "vertices": int(len(compact_vertices)),
      "triangles": int(len(compact_faces)),
  }


def _as_float_list(values: Iterable[float]) -> list[float]:
  return [round(float(value), 9) for value in values]


def main() -> None:
  args = _parse_args()
  output_dir = args.output.resolve()
  output_dir.mkdir(parents=True, exist_ok=True)

  print("Loading GNM v3 HEAD model...")
  model = gnm_numpy.GNM.from_local(
      version=gnm_numpy.GNMMajorVersion.V3,
      variant=gnm_numpy.GNMVariant.HEAD,
  )
  print("Loading GNM identity semantic sampler...")
  sampler = semantic_sampler.IdentitySampler()

  triangles = np.asarray(model.triangles, dtype=np.int64)
  component_masks = {
      component: _group_face_mask(model, group_name)
      for component, group_name in COMPONENT_GROUPS.items()
  }
  metadata: dict[str, object] = {
      "generator": "tools/characters/generate_gnm_asian_heads.py",
      "gnm_source_revision": _git_revision(args.gnm_source.resolve()),
      "gnm_version": "v3",
      "gnm_variant": "HEAD",
      "semantic_ethnicity_label": "ASIAN",
      "semantic_label_scope_note": (
          "GNM exposes a broad Asian sampler category. These samples are "
          "geometry references, not Chinese-ethnicity classifications."
      ),
      "expression": "neutral (zero expression coefficients)",
      "topology": {
          "source_vertices": int(model.num_vertices),
          "source_triangles": int(len(triangles)),
          "identity_dimensions": int(model.identity_dim),
          "expression_dimensions": int(model.expression_dim),
      },
      "seeds": [int(seed) for seed in args.seeds],
      "samples": [],
  }

  gender_classes = (
      ("female", semantic_sampler.Gender.FEMALE),
      ("male", semantic_sampler.Gender.MALE),
  )
  for gender_name, gender_class in gender_classes:
    for seed in args.seeds:
      sample_id = f"{gender_name}-s{seed:03d}"
      print(f"Generating {sample_id}...")
      identity = sampler.sample_identity(
          gender_class,
          semantic_sampler.Ethnicity.ASIAN,
          num_samples=1,
          rng=np.random.default_rng(seed),
      )[0]
      vertices = np.asarray(model(identity=identity), dtype=np.float64)
      sample_dir = output_dir / sample_id
      components: dict[str, dict[str, object]] = {}
      for component, face_mask in component_masks.items():
        relative_path = Path(sample_id) / f"{component}.obj"
        counts = _write_obj(
            output_dir / relative_path,
            vertices,
            triangles,
            face_mask,
            f"{sample_id}_{component}",
        )
        components[component] = {
            "path": relative_path.as_posix(),
            **counts,
        }

      sample_record = {
          "id": sample_id,
          "gender_label": gender_name.upper(),
          "seed": int(seed),
          "identity_parameter_min": round(float(identity.min()), 9),
          "identity_parameter_max": round(float(identity.max()), 9),
          "bounds_min_m": _as_float_list(vertices.min(axis=0)),
          "bounds_max_m": _as_float_list(vertices.max(axis=0)),
          "span_m": _as_float_list(np.ptp(vertices, axis=0)),
          "components": components,
      }
      samples = metadata["samples"]
      assert isinstance(samples, list)
      samples.append(sample_record)

  metadata_path = output_dir / "metadata.json"
  metadata_path.write_text(
      json.dumps(metadata, indent=2, sort_keys=True) + "\n",
      encoding="utf-8",
  )
  print(f"Wrote {len(metadata['samples'])} samples to {output_dir}")
  print(f"Metadata: {metadata_path}")


if __name__ == "__main__":
  main()
